import type { Metadata } from 'next';
import { i18n, Locale } from '@/i18n-config';
import { GeistSans } from 'geist/font/sans';
import { Toaster } from '@/components/ui/sonner';
import '../globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Providers from '../providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className={GeistSans.className}>
        <Providers>
          <ThemeProvider>
            {children}
            <Toaster />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
