name: End to End Tests

on: push

env:
  NODE_VERSION: 20

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Install cypress
        run: bunx cypress install

  test:
    runs-on: ubuntu-latest
    needs: install
    name: Test
    steps:
      - name: Run tests
        run: bun run e2e-test:headless

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots