name: Unit tests

on: [push, pull_request]

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests and collect coverage
        run: bun run unit-test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3